/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.gson.Gson;
import java.util.Map;

public class App {
    public String getGreeting(){
        var gson = new Gson();
        return gson.toJson(Map.of("Hello", "world"));
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}