/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.gson.Gson;
import java.util.Map;

public class App {
  public static void main(String[] args) {
    var gson = new Gson();
    System.out.println(gson.toJson(Map.of("hello", "world")));
  }
}